#!/bin/sh

export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/lib:/lib:/lib/ts"

if [ ! -d "/dev/pts" ]; then
        mkdir /dev/pts
        mount -t devpts devpts /dev/pts
fi
telnetd -l /bin/sh &

#VIDEODOOR_PATH=`pwd`
VIDEODOOR_PATH="mnt/nand1-1"
VIDEODOOR_MP="/mnt/videodoor"
VIDEODOOR_APP="/mnt/ml"

# To mount VIDEODOOR ROMFS file
if [ -f $VIDEODOOR_PATH/ml8_app.bin ]; then
	if [ ! -d $VIDEODOOR_APP ]; then mkdir -p $VIDEODOOR_APP; fi
	if [ ! -d $VIDEODOOR_MP ]; then mkdir -p $VIDEODOOR_MP; fi
	mount -t romfs $VIDEODOOR_PATH/ml8_app.bin $VIDEODOOR_APP
	mount -t romfs $VIDEODOOR_PATH/ml8_res.bin $VIDEODOOR_MP
	if [ ! "$?" == "0" ]; then
		echo "Mount ml8_app.bin failure."
		#exit 1
	fi

	# Execute VIDEODOOR
	cd $VIDEODOOR_MP
	ln -s $VIDEODOOR_MP /mnt/mg
	cd /mnt/mg
	cp -af etc/MiniGUI.cfg /etc
	./auNetUpgrade&
	cd $VIDEODOOR_APP
	./main&
else
	echo "File non-exits!!!"
	#exit 1
fi
